### ISSUE TITLE
upload of notebook fails with a 500 error

### ISSUE THREAD

**Issue by tubaman** [nbgallery/nbgallery#168]
After running `docker-compose -f docker-compose.yml -f docker-compose-with-jupyter.yml up` and logging in as admin, my first notebook upload fails with a 500.  Here's the error:

```
solr_1       | 2020-04-29 23:36:07.535 ERROR (qtp1521083627-14) [   ] o.a.s.s.HttpSolrCall null:org.apache.solr.core.SolrCoreInitializationException: SolrCore 'default' is not available due to init failure: java.nio.file.AccessDeniedException: /opt/solr/server/solr/default/data/snapshot_metadata
solr_1       | 	at org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:1490)
solr_1       | 	at org.apache.solr.servlet.HttpSolrCall.init(HttpSolrCall.java:251)
solr_1       | 	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:471)
solr_1       | 	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:384)
solr_1       | 	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:330)
solr_1       | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1629)
solr_1       | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
solr_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
solr_1       | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
solr_1       | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
solr_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
solr_1       | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
solr_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
solr_1       | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
solr_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
solr_1       | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
solr_1       | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
solr_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
solr_1       | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
solr_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
solr_1       | 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
solr_1       | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
solr_1       | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
solr_1       | 	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
solr_1       | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
solr_1       | 	at org.eclipse.jetty.server.Server.handle(Server.java:530)
solr_1       | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
solr_1       | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
solr_1       | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
solr_1       | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
solr_1       | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
solr_1       | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
solr_1       | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
solr_1       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
solr_1       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
solr_1       | 	at java.base/java.lang.Thread.run(Thread.java:844)
solr_1       | Caused by: org.apache.solr.common.SolrException: java.nio.file.AccessDeniedException: /opt/solr/server/solr/default/data/snapshot_metadata
solr_1       | 	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:1008)
solr_1       | 	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:863)
solr_1       | 	at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1040)
solr_1       | 	at org.apache.solr.core.CoreContainer.lambda$load$13(CoreContainer.java:640)
solr_1       | 	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:197)
solr_1       | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
solr_1       | 	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:188)
solr_1       | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
solr_1       | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
solr_1       | 	... 1 more
solr_1       | Caused by: java.lang.IllegalStateException: java.nio.file.AccessDeniedException: /opt/solr/server/solr/default/data/snapshot_metadata
solr_1       | 	at org.apache.solr.core.SolrCore.initSnapshotMetaDataManager(SolrCore.java:502)
solr_1       | 	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:948)
solr_1       | 	... 9 more
solr_1       | Caused by: java.nio.file.AccessDeniedException: /opt/solr/server/solr/default/data/snapshot_metadata
solr_1       | 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
solr_1       | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
solr_1       | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
solr_1       | 	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:385)
solr_1       | 	at java.base/java.nio.file.Files.createDirectory(Files.java:682)
solr_1       | 	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:789)
solr_1       | 	at java.base/java.nio.file.Files.createDirectories(Files.java:775)
solr_1       | 	at org.apache.lucene.store.FSDirectory.<init>(FSDirectory.java:157)
solr_1       | 	at org.apache.lucene.store.MMapDirectory.<init>(MMapDirectory.java:159)
solr_1       | 	at org.apache.lucene.store.MMapDirectory.<init>(MMapDirectory.java:112)
solr_1       | 	at org.apache.lucene.store.FSDirectory.open(FSDirectory.java:197)
solr_1       | 	at org.apache.solr.core.NRTCachingDirectoryFactory.create(NRTCachingDirectoryFactory.java:55)
solr_1       | 	at org.apache.solr.core.CachingDirectoryFactory.get(CachingDirectoryFactory.java:347)
solr_1       | 	at org.apache.solr.core.SolrCore.initSnapshotMetaDataManager(SolrCore.java:498)
solr_1       | 	... 10 more
solr_1       | 
solr_1       | 2020-04-29 23:36:07.629 ERROR (qtp1521083627-19) [   ] o.a.s.s.HttpSolrCall null:org.apache.solr.core.SolrCoreInitializationException: SolrCore 'default' is not available due to init failure: java.nio.file.AccessDeniedException: /opt/solr/server/solr/default/data/snapshot_metadata
solr_1       | 	at org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:1490)
solr_1       | 	at org.apache.solr.servlet.HttpSolrCall.init(HttpSolrCall.java:251)
solr_1       | 	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:471)
solr_1       | 	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:384)
solr_1       | 	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:330)
solr_1       | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1629)
solr_1       | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
solr_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
solr_1       | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
solr_1       | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
solr_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
solr_1       | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
solr_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
solr_1       | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
solr_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
solr_1       | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
solr_1       | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
solr_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
solr_1       | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
solr_1       | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
solr_1       | 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
solr_1       | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
solr_1       | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
solr_1       | 	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
solr_1       | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
solr_1       | 	at org.eclipse.jetty.server.Server.handle(Server.java:530)
solr_1       | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
solr_1       | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
solr_1       | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
solr_1       | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
solr_1       | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
solr_1       | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
solr_1       | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
solr_1       | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
solr_1       | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
solr_1       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
solr_1       | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
solr_1       | 	at java.base/java.lang.Thread.run(Thread.java:844)
solr_1       | Caused by: org.apache.solr.common.SolrException: java.nio.file.AccessDeniedException: /opt/solr/server/solr/default/data/snapshot_metadata
solr_1       | 	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:1008)
solr_1       | 	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:863)
solr_1       | 	at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1040)
solr_1       | 	at org.apache.solr.core.CoreContainer.lambda$load$13(CoreContainer.java:640)
solr_1       | 	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:197)
solr_1       | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
solr_1       | 	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:188)
solr_1       | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
solr_1       | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
solr_1       | 	... 1 more
solr_1       | Caused by: java.lang.IllegalStateException: java.nio.file.AccessDeniedException: /opt/solr/server/solr/default/data/snapshot_metadata
solr_1       | 	at org.apache.solr.core.SolrCore.initSnapshotMetaDataManager(SolrCore.java:502)
solr_1       | 	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:948)
solr_1       | 	... 9 more
solr_1       | Caused by: java.nio.file.AccessDeniedException: /opt/solr/server/solr/default/data/snapshot_metadata
solr_1       | 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
solr_1       | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
solr_1       | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
solr_1       | 	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:385)
solr_1       | 	at java.base/java.nio.file.Files.createDirectory(Files.java:682)
solr_1       | 	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:789)
solr_1       | 	at java.base/java.nio.file.Files.createDirectories(Files.java:775)
solr_1       | 	at org.apache.lucene.store.FSDirectory.<init>(FSDirectory.java:157)
solr_1       | 	at org.apache.lucene.store.MMapDirectory.<init>(MMapDirectory.java:159)
solr_1       | 	at org.apache.lucene.store.MMapDirectory.<init>(MMapDirectory.java:112)
solr_1       | 	at org.apache.lucene.store.FSDirectory.open(FSDirectory.java:197)
solr_1       | 	at org.apache.solr.core.NRTCachingDirectoryFactory.create(NRTCachingDirectoryFactory.java:55)
solr_1       | 	at org.apache.solr.core.CachingDirectoryFactory.get(CachingDirectoryFactory.java:347)
solr_1       | 	at org.apache.solr.core.SolrCore.initSnapshotMetaDataManager(SolrCore.java:498)
solr_1       | 	... 10 more
solr_1       | 
nbgallery_1  | Error during failsafe response: RSolr::Error::Http - 500 Internal Server Error
nbgallery_1  | Error: 'SolrCore \'default\' is not available due to init failure: java.nio.file.AccessDeniedException: /opt/solr/server/solr/default/data/snapshot_metadata',
nbgallery_1  | 
nbgallery_1  | URI: http://solr:8983/solr/default/update?wt=ruby
nbgallery_1  | Request Headers: {"Content-Type"=>"text/xml"}
nbgallery_1  | Request Data: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><commit softCommit=\"false\"/>"
nbgallery_1  | 
nbgallery_1  | Backtrace: /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:288:in `adapt_response'
nbgallery_1  | /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:189:in `execute'
nbgallery_1  | /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:175:in `send_and_receive'
nbgallery_1  | /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/sunspot_rails-2.2.7/lib/sunspot/rails/solr_instrumentation.rb:16:in `block in send_and_receive_with_as_instrumentation'
nbgallery_1  | /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/notifications.rb:164:in `block in instrument'
nbgallery_1  | /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
nbgallery_1  | /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/notifications.rb:164:in `instrument'
nbgallery_1  | /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/sunspot_rails-2.2.7/lib/sunspot/rails/solr_instrumentation.rb:15:in `send_and_receive_with_as_instrumentation'
nbgallery_1  | (eval):2:in `post'
nbgallery_1  | /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:84:in `update'
nbgallery_1  | /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:113:in `commit'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:288:in `adapt_response'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:189:in `execute'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:175:in `send_and_receive'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/sunspot_rails-2.2.7/lib/sunspot/rails/solr_instrumentation.rb:16:in `block in send_and_receive_with_as_instrumentation'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/notifications.rb:164:in `block in instrument'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/notifications.rb:164:in `instrument'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/sunspot_rails-2.2.7/lib/sunspot/rails/solr_instrumentation.rb:15:in `send_and_receive_with_as_instrumentation'
nbgallery_1  |   (eval):2:in `post'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:84:in `update'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/rsolr-1.1.2/lib/rsolr/client.rb:113:in `commit'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/sunspot-2.2.7/lib/sunspot/session.rb:123:in `commit'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/sunspot-2.2.7/lib/sunspot/session.rb:220:in `commit_if_dirty'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/sunspot-2.2.7/lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in `commit_if_dirty'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/sunspot-2.2.7/lib/sunspot.rb:554:in `commit_if_dirty'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/sunspot_rails-2.2.7/lib/sunspot/rails/request_lifecycle.rb:28:in `block (2 levels) in included'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:446:in `instance_exec'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:446:in `block in make_lambda'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:239:in `block in halting'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:506:in `block in call'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:506:in `each'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:506:in `call'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/notifications.rb:164:in `block in instrument'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/notifications.rb:164:in `instrument'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.11.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/abstract_controller/base.rb:137:in `process'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/actionview-4.2.11.1/lib/action_view/rendering.rb:30:in `process'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_controller/metal.rb:196:in `dispatch'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_controller/metal.rb:237:in `block in action'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/gaffe-1.2.0/lib/gaffe.rb:22:in `block in enable!'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/show_exceptions.rb:47:in `render_exception'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/show_exceptions.rb:35:in `rescue in call'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/show_exceptions.rb:29:in `call'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/rack/logger.rb:38:in `call_app'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/rack/logger.rb:20:in `block in call'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/tagged_logging.rb:26:in `tagged'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/tagged_logging.rb:68:in `tagged'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/rack/logger.rb:20:in `call'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/rack-1.6.12/lib/rack/methodoverride.rb:22:in `call'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/rack-1.6.12/lib/rack/runtime.rb:18:in `call'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.11.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.11.1/lib/action_dispatch/middleware/static.rb:120:in `call'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/rack-1.6.12/lib/rack/sendfile.rb:113:in `call'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/rack-cors-1.0.6/lib/rack/cors.rb:98:in `call'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/engine.rb:518:in `call'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/railties-4.2.11.1/lib/rails/application.rb:165:in `call'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/rack-1.6.12/lib/rack/content_length.rb:15:in `call'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/puma-3.12.2/lib/puma/configuration.rb:227:in `call'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/puma-3.12.2/lib/puma/server.rb:674:in `handle_request'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/puma-3.12.2/lib/puma/server.rb:476:in `process_client'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/puma-3.12.2/lib/puma/server.rb:334:in `block in run'
nbgallery_1  |   /usr/src/nbgallery/vendor/bundle/ruby/2.3.0/gems/puma-3.12.2/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

**Comment by jeffyjefflabs** [comment]
This looks like the same issue as #38; can you try the workaround mentioned there?  I'm not sure if there's a better fix, maybe in newer versions of docker/compose?  I haven't looked into it in a while.

**Comment by mcrutch** [comment]
Still not something that can be fixed in docker-compose and I have added a bit more documentation for using docker-compose in #257 but nothing we can do about it.
