### ISSUE TITLE
Solr tags_text is ont a valid field name

### ISSUE THREAD

**Issue by cccs-cat001** [nbgallery/nbgallery#263]
Hi, 

   When I try to search in nbgallery I get a 500 error, and the logs says
```
Error: 'org.apache.solr.search.SyntaxError: Query Field \'tags_text\' is not a valid field name',
```

Any idea how to fix it? I'm running solr externally, version 8.5.2

**Comment by mcrutch** [comment]
That sounds like it is missing the sunspot configuration for the index.

**Comment by cccs-cat001** [comment]
Under /opt/solr/server/solr, I have
```
$ tree -L 2 -p
.
|-- [drwxrwxrwx]  _default
|   |-- [drwxrwxrwx]  conf
|   |-- [-rwxrwxrwx]  core.properties
|   |-- [drwxrwxrwx]  lang
|   |-- [-rwxrwxrwx]  managed-schema
|   |-- [-rwxrwxrwx]  params.json
|   |-- [-rwxrwxrwx]  protwords.txt
|   |-- [-rwxrwxrwx]  solrconfig.xml
|   |-- [-rwxrwxrwx]  stopwords.txt
|   `-- [-rwxrwxrwx]  synonyms.txt
|-- [-rwxrwxrwx]  solr.xml
`-- [-rwxrwxrwx]  zoo.cfg
```
(And under conf is another `managed-schema`). Which is the same stuff as the docker-compose wants no? Or am I missing something?

**Comment by mcrutch** [comment]
For the solr 8 those get mapped to /var/solr/data/, not /opt/solr/server/solr.  (which is a change from solr 7) https://github.com/docker-solr/docker-solr/blob/master/README.md#running-solr-with-host-mounted-directories

**Comment by mcrutch** [comment]
Were you able to get this working?

**Comment by cccs-cat001** [comment]
Hi, no I'm still playing around with it. I mount everything to /var/solr/data instead of before, but I'm back to my original issue where I can't even upload a notebook

**Comment by mcrutch** [comment]
Make sure the data directories have the correct owner/group (8983:8983 on the host, or solr/solr in the container)
https://github.com/nbgallery/nbgallery/issues/38

Are there any errors in /usr/src/nbgallery/logs/production.log inside the NBGallery container?  how about the logs from the Solr container?

**Comment by cccs-cat001** [comment]
Hmm.. All the files are root:solr, but it's rwx for u/g/o so that should be fine eh..? 

When I try to upload a notebook I get `Error: 'SolrCore \'default\' is not available due to init failure: ',`

**Comment by mcrutch** [comment]
Everything I am seeing says it has to be solr:solr, but I would look in the logs for your solr container

**Comment by cccs-cat001** [comment]
Those logs say: 
```
o.a.s.s.HttpSolrCall null:org.apache.solr.core 
 solr     at org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:1791)                          
 solr     at org.apache.solr.servlet.HttpSolrCall.init(HttpSolrCall.java:256)                             
 solr     at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:539)                             
 solr     at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:420)             
 solr     at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:352)             
 solr     at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1596)      
 solr     at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)                   
 solr     at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)                
 solr     at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)                  
 solr     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)              
 solr     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)            
 solr     at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)           
 solr     at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)            
 solr     at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)           
 solr     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)             
 solr     at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)                    
 solr     at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)            
 solr     at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)             
 solr     at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)  
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)                
 solr     at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.ja 
 solr     at org.eclipse.jetty.server.handler.InetAccessHandler.handle(InetAccessHandler.java:177)        
 solr     at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)        
 solr     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)              
 solr     at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:322)             
 solr     at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)              
 solr     at org.eclipse.jetty.server.Server.handle(Server.java:500)                                      
 solr     at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)                   
 solr     at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)                          
 solr     at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)                            
 solr     at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)                  
 solr     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)  
 solr     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)                            
 solr     at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)                         
 solr     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)       
 solr     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)     
 solr     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)    
 solr     at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)           
 solr     at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecut 
 solr     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)             
 solr     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)         
 solr     at java.base/java.lang.Thread.run(Unknown Source)                                               
 solr Caused by: org.apache.solr.common.SolrException:                                                    
 solr     at org.apache.solr.cloud.ZkController.preRegister(ZkController.java:1795)                       
 solr     at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1299)             
 solr     at org.apache.solr.core.CoreContainer.lambda$load$13(CoreContainer.java:802)                    
 solr     at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecu 
 solr     at java.base/java.util.concurrent.FutureTask.run(Unknown Source)                                
 solr     at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(Executo 
 solr     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)                  
 solr     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)                 
 solr     ... 1 more                                                                                      
 solr Caused by: org.apache.solr.common.SolrException: Could not find collection : default                
 solr     at org.apache.solr.common.cloud.ClusterState.getCollection(ClusterState.java:116)               
 solr     at org.apache.solr.core.CoreContainer.repairCoreProperty(CoreContainer.java:2003)               
 solr     at org.apache.solr.cloud.ZkController.checkStateInZk(ZkController.java:1825)                    
 solr     at org.apache.solr.cloud.ZkController.preRegister(ZkController.java:1764)                       
 solr     ... 8 more 
```

**Comment by cccs-cat001** [comment]
In the solr UI the 'default' collection is there, and there is a default core as well, but that says it's not available due to an init failure. There's also a default_shard1_replica_n1 core, which seems to be alive

**Comment by mcrutch** [comment]
All of this is based off using this branch - https://github.com/nbgallery/nbgallery/tree/update-solr-container (Because SOLR8 is significantly different than SOLR7 and the configs are different)
Based off the paths in [this docker-compose.yml](https://github.com/nbgallery/nbgallery/blob/update-solr-container/docker-compose.yml):

>       - "${PWD}/docker/config/solr:/var/solr/data"
>       - "${PWD}/docker/data/solr/data:/var/solr/data/default/data"

sudo chown -R 8983:8983 ./docker/config/solr
mkdir -p ./docker/data/solr/data
sudo chown -R 8983:8983 ./docker/data/solr
Obviously you will have to change these paths to the appropriate location for your application

I just took these exact steps on a machine that never had the containers and it worked.  The solr configs from the current master branch WILL NOT work (they only work with SOLR 7)

**Comment by cccs-cat001** [comment]
Alright. 
Destroyed everything on the cluster
Using image solr:8.5.2
Using that branch :heavy_check_mark: (pulled and cleared my current changes)
/var/solr/data contains what's in <nbgallery>/docker/config/solr :heavy_check_mark: 
created /var/solr/data/default/data :heavy_check_mark: 
Logs from solr as it starts up: 
```Starting Solr 
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
2020-08-04 19:27:36.840 INFO  (main) [   ] o.e.j.u.log Logging initialized @1426ms to org.eclipse.jetty.util.log.Slf4jLog
2020-08-04 19:27:37.016 INFO  (main) [   ] o.e.j.s.Server jetty-9.4.24.v20191120; built: 2019-11-20T21:37:49.771Z; git: 363d5f2df3a8a28de40604320230664b9c793c16; jvm 11.0.8+10
2020-08-04 19:27:37.108 INFO  (main) [   ] o.e.j.d.p.ScanningAppProvider Deployment monitor [file:///opt/solr-8.5.2/server/contexts/] at interval 0
2020-08-04 19:27:37.356 INFO  (main) [   ] o.e.j.w.StandardDescriptorProcessor NO JSP Support for /solr, did not find org.apache.jasper.servlet.JspServlet
2020-08-04 19:27:37.365 INFO  (main) [   ] o.e.j.s.session DefaultSessionIdManager workerName=node0
2020-08-04 19:27:37.365 INFO  (main) [   ] o.e.j.s.session No SessionScavenger set, using defaults
2020-08-04 19:27:37.367 INFO  (main) [   ] o.e.j.s.session node0 Scavenging every 660000ms
2020-08-04 19:27:37.434 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter Using logger factory org.apache.logging.slf4j.Log4jLoggerFactory
2020-08-04 19:27:37.438 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter  ___      _       Welcome to Apache Solr™ version 8.5.2
2020-08-04 19:27:37.441 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter / __| ___| |_ _   Starting in cloud mode on port 8988
2020-08-04 19:27:37.441 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter \__ \/ _ \ | '_|  Install dir: /opt/solr
2020-08-04 19:27:37.441 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter |___/\___/_|_|    Start time: 2020-08-04T19:27:37.441678Z
2020-08-04 19:27:37.441 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter Log level override, property solr.log.level=INFO
2020-08-04 19:27:37.480 INFO  (main) [   ] o.a.s.c.SolrResourceLoader Using system property solr.solr.home: /var/solr/data
2020-08-04 19:27:37.527 INFO  (main) [   ] o.a.s.c.c.ConnectionManager Waiting for client to connect to ZooKeeper
2020-08-04 19:27:37.563 INFO  (zkConnectionManagerCallback-2-thread-1) [   ] o.a.s.c.c.ConnectionManager zkClient has connected
2020-08-04 19:27:37.563 INFO  (main) [   ] o.a.s.c.c.ConnectionManager Client is connected to ZooKeeper
2020-08-04 19:27:37.674 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter Loading solr.xml from SolrHome (not found in ZooKeeper)
2020-08-04 19:27:37.677 INFO  (main) [   ] o.a.s.c.SolrXmlConfig Loading container configuration from /var/solr/data/solr.xml
2020-08-04 19:27:37.781 INFO  (main) [   ] o.a.s.c.SolrXmlConfig MBean server found: com.sun.jmx.mbeanserver.JmxMBeanServer@39d9314d, but no JMX reporters were configured - adding default JMX reporter.
2020-08-04 19:27:38.476 INFO  (main) [   ] o.a.s.h.c.HttpShardHandlerFactory Host whitelist initialized: WhitelistHostChecker [whitelistHosts=null, whitelistHostCheckingEnabled=true]
2020-08-04 19:27:38.600 WARN  (main) [   ] o.e.j.u.s.S.config Trusting all certificates configured for Client@3e47a03[provider=null,keyStore=null,trustStore=null]
2020-08-04 19:27:38.601 WARN  (main) [   ] o.e.j.u.s.S.config No Client EndPointIdentificationAlgorithm configured for Client@3e47a03[provider=null,keyStore=null,trustStore=null]
2020-08-04 19:27:38.774 WARN  (main) [   ] o.e.j.u.s.S.config Trusting all certificates configured for Client@6f94fb9d[provider=null,keyStore=null,trustStore=null]
2020-08-04 19:27:38.775 WARN  (main) [   ] o.e.j.u.s.S.config No Client EndPointIdentificationAlgorithm configured for Client@6f94fb9d[provider=null,keyStore=null,trustStore=null]
2020-08-04 19:27:38.785 INFO  (main) [   ] o.a.s.c.ZkContainer Zookeeper client=nbgallery-zookeeper-headless:2181
2020-08-04 19:27:38.821 INFO  (main) [   ] o.a.s.c.c.ConnectionManager Waiting for client to connect to ZooKeeper
2020-08-04 19:27:38.835 INFO  (zkConnectionManagerCallback-9-thread-1) [   ] o.a.s.c.c.ConnectionManager zkClient has connected
2020-08-04 19:27:38.836 INFO  (main) [   ] o.a.s.c.c.ConnectionManager Client is connected to ZooKeeper
2020-08-04 19:27:38.929 INFO  (main) [   ] o.a.s.c.OverseerElectionContext I am going to be the leader nbgallery-solr-0.nbgallery-solr-headless.nbgallery:8988_solr
2020-08-04 19:27:38.936 INFO  (main) [   ] o.a.s.c.Overseer Overseer (id=72198497252999204-nbgallery-solr-0.nbgallery-solr-headless.nbgallery:8988_solr-n_0000000007) starting
2020-08-04 19:27:39.032 INFO  (main) [   ] o.a.s.c.ZkController Register node as live in ZooKeeper:/live_nodes/nbgallery-solr-0.nbgallery-solr-headless.nbgallery:8988_solr
2020-08-04 19:27:39.035 INFO  (OverseerStateUpdate-72198497252999204-nbgallery-solr-0.nbgallery-solr-headless.nbgallery:8988_solr-n_0000000007) [   ] o.a.s.c.Overseer Starting to work on the main queue : nbgallery-solr-0.nbgallery-solr-headless.nbgallery:8988_solr
2020-08-04 19:27:39.055 INFO  (zkCallback-8-thread-1) [   ] o.a.s.c.c.ZkStateReader Updated live nodes from ZooKeeper... (0) -> (1)
2020-08-04 19:27:39.107 INFO  (main) [   ] o.a.s.p.PackageLoader /packages.json updated to version -1
2020-08-04 19:27:39.121 WARN  (main) [   ] o.a.s.c.CoreContainer Not all security plugins configured!  authentication=disabled authorization=disabled.  Solr is only as secure as you make it. Consider configuring authentication/authorization before exposing Solr to users internal or external.  See https://s.apache.org/solrsecurity for more info
2020-08-04 19:27:39.231 INFO  (main) [   ] o.a.s.h.a.MetricsHistoryHandler No .system collection, keeping metrics history in memory.
2020-08-04 19:27:39.304 INFO  (main) [   ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.node' (registry 'solr.node') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@39d9314d
2020-08-04 19:27:39.305 INFO  (main) [   ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.jvm' (registry 'solr.jvm') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@39d9314d
2020-08-04 19:27:39.310 INFO  (main) [   ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.jetty' (registry 'solr.jetty') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@39d9314d
2020-08-04 19:27:39.452 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Found 1 core definitions underneath /var/solr/data
2020-08-04 19:27:39.453 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Cores are: [default]
2020-08-04 19:27:39.468 INFO  (coreLoadExecutor-13-thread-1-processing-n:nbgallery-solr-0.nbgallery-solr-headless.nbgallery:8988_solr) [   ] o.a.s.c.TransientSolrCoreCacheDefault Allocating transient cache for 2147483647 transient cores
2020-08-04 19:27:39.545 INFO  (coreLoadExecutor-13-thread-1-processing-n:nbgallery-solr-0.nbgallery-solr-headless.nbgallery:8988_solr) [   ] o.a.s.c.RequestParams conf resource params.json loaded . version : 1 
2020-08-04 19:27:39.546 INFO  (coreLoadExecutor-13-thread-1-processing-n:nbgallery-solr-0.nbgallery-solr-headless.nbgallery:8988_solr) [   ] o.a.s.c.RequestParams request params refreshed to version 1
2020-08-04 19:27:39.554 INFO  (coreLoadExecutor-13-thread-1-processing-n:nbgallery-solr-0.nbgallery-solr-headless.nbgallery:8988_solr) [   ] o.a.s.c.SolrResourceLoader [default] Added 62 libs to classloader, from paths: [/opt/solr/contrib/clustering/lib, /opt/solr/contrib/extraction/lib, /opt/solr/contrib/langid/lib, /opt/solr/contrib/velocity/lib, /opt/solr/dist]
2020-08-04 19:27:39.565 INFO  (main) [   ] o.e.j.s.h.ContextHandler Started o.e.j.w.WebAppContext@514eedd8{/solr,file:///opt/solr-8.5.2/server/solr-webapp/webapp/,AVAILABLE}{/opt/solr-8.5.2/server/solr-webapp/webapp}
2020-08-04 19:27:39.573 INFO  (main) [   ] o.e.j.s.AbstractConnector Started ServerConnector@56ace400{HTTP/1.1,[http/1.1, h2c]}{0.0.0.0:8988}
2020-08-04 19:27:39.574 INFO  (main) [   ] o.e.j.s.Server Started @4163ms
2020-08-04 19:27:39.788 INFO  (coreLoadExecutor-13-thread-1-processing-n:nbgallery-solr-0.nbgallery-solr-headless.nbgallery:8988_solr) [   ] o.a.s.c.SolrConfig Using Lucene MatchVersion: 7.3.0
2020-08-04 19:27:39.941 INFO  (coreLoadExecutor-13-thread-1-processing-n:nbgallery-solr-0.nbgallery-solr-headless.nbgallery:8988_solr) [   ] o.a.s.s.IndexSchema [default] Schema name=default-config
2020-08-04 19:27:40.532 INFO  (coreLoadExecutor-13-thread-1-processing-n:nbgallery-solr-0.nbgallery-solr-headless.nbgallery:8988_solr) [   ] o.a.s.s.IndexSchema Loaded schema default-config/1.6 with uniqueid field id
2020-08-04 19:27:40.663 ERROR (coreLoadExecutor-13-thread-1-processing-n:nbgallery-solr-0.nbgallery-solr-headless.nbgallery:8988_solr) [c:default   x:default] o.a.s.c.CoreContainer Could not repair coreNodeName in core.properties file for core default
2020-08-04 19:27:40.663 ERROR (coreLoadExecutor-13-thread-1-processing-n:nbgallery-solr-0.nbgallery-solr-headless.nbgallery:8988_solr) [c:default   x:default] o.a.s.c.ZkController  => org.apache.solr.common.SolrException: No coreNodeName for CoreDescriptor[name=default;instanceDir=/var/solr/data/default]
	at org.apache.solr.cloud.ZkController.checkStateInZk(ZkController.java:1826)
org.apache.solr.common.SolrException: No coreNodeName for CoreDescriptor[name=default;instanceDir=/var/solr/data/default]
	at org.apache.solr.cloud.ZkController.checkStateInZk(ZkController.java:1826) ~[?:?]
	at org.apache.solr.cloud.ZkController.preRegister(ZkController.java:1764) ~[?:?]
	at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1299) ~[?:?]
	at org.apache.solr.core.CoreContainer.lambda$load$13(CoreContainer.java:802) ~[?:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:202) ~[metrics-core-4.1.2.jar:4.1.2]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:210) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
2020-08-04 19:27:40.664 ERROR (coreContainerWorkExecutor-2-thread-1-processing-n:nbgallery-solr-0.nbgallery-solr-headless.nbgallery:8988_solr) [   ] o.a.s.c.CoreContainer Error waiting for SolrCore to be loaded on startup => org.apache.solr.common.SolrException: Unable to create core [default]
	at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1327)
org.apache.solr.common.SolrException: Unable to create core [default]
	at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1327) ~[?:?]
	at org.apache.solr.core.CoreContainer.lambda$load$13(CoreContainer.java:802) ~[?:?]
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:202) ~[metrics-core-4.1.2.jar:4.1.2]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:210) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: org.apache.solr.common.SolrException: 
	at org.apache.solr.cloud.ZkController.preRegister(ZkController.java:1795) ~[?:?]
	at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1299) ~[?:?]
	... 7 more
Caused by: org.apache.solr.common.SolrException: No coreNodeName for CoreDescriptor[name=default;instanceDir=/var/solr/data/default]
	at org.apache.solr.cloud.ZkController.checkStateInZk(ZkController.java:1826) ~[?:?]
	at org.apache.solr.cloud.ZkController.preRegister(ZkController.java:1764) ~[?:?]
	at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1299) ~[?:?]
	... 7 more
``` 
/var/solr/data (After solr has started): 
```
# tree -L 2 
.
|-- default
|   |-- conf
|   |   `-- managed-schema
|   |-- core.properties
|   |-- data
|   |-- lang (Removed all these from output)
|   |-- managed-schema
|   |-- params.json
|   |-- protwords.txt
|   |-- solrconfig.xml
|   |-- stopwords.txt
|   `-- synonyms.txt
|-- filestore
|-- solr.xml
|-- userfiles
`-- zoo.cfg
```

Any other info I can provide that might be helpful?

**Comment by cccs-cat001** [comment]
Alright. After a few minutes of processing what you said, and processing my terminal output, I realized that solr is launching zookeeper along side it. I removed all that and behold. A working nbgallery. Finally. Thank you for your assistance :smile: Sorry I'm weak lol

**Comment by cccs-cat001** [comment]
I've created a helm chart to deploy nbgallery to a kubernetes cluster. Would I be able to contribute that to this repo? I've got a bit of cleaning up I need to do first.

**Comment by mcrutch** [comment]
Probably best to put the Helm chart in a different repo to keep things clean, so I created this https://github.com/nbgallery/nbgallery-helm.  Fork that repo and then you can submit a pull request when you helm chart is ready.

**Comment by cccs-cat001** [comment]
Cool, thanks :smile:
