### ISSUE TITLE
Migration 20210726183045_change_to_utf8_mb4.rb doesn't work

### ISSUE THREAD

**Issue by pffont** [nbgallery/nbgallery#654]
I'm getting this error when running the nbgallery container:

```
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Can't DROP 'index_clicks_on_org'; check that column/key exists: DROP INDEX index_clicks_on_org on clicks
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `handle_interrupt'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `query'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:665:in `block in method_missing'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:634:in `say_with_time'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:654:in `method_missing'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:416:in `method_missing'
/usr/src/nbgallery/db/migrate/20210726183045_change_to_utf8_mb4.rb:3:in `up'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:571:in `up'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:611:in `exec_migration'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:591:in `block in migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:590:in `migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:768:in `migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:1071:in `ddl_transaction'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:984:in `block in migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:980:in `each'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:980:in `migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:823:in `up'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:801:in `migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: Can't DROP 'index_clicks_on_org'; check that column/key exists: DROP INDEX index_clicks_on_org on clicks
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `handle_interrupt'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `query'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:665:in `block in method_missing'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:634:in `say_with_time'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:654:in `method_missing'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:416:in `method_missing'
/usr/src/nbgallery/db/migrate/20210726183045_change_to_utf8_mb4.rb:3:in `up'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:571:in `up'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:611:in `exec_migration'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:591:in `block in migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:590:in `migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:768:in `migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:1071:in `ddl_transaction'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:984:in `block in migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:980:in `each'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:980:in `migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:823:in `up'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:801:in `migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'

Caused by:
Mysql2::Error: Can't DROP 'index_clicks_on_org'; check that column/key exists
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `handle_interrupt'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `query'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `block in execute'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.11.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:317:in `execute'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/mysql2_adapter.rb:217:in `execute'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:665:in `block in method_missing'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:634:in `say_with_time'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:654:in `method_missing'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:416:in `method_missing'
/usr/src/nbgallery/db/migrate/20210726183045_change_to_utf8_mb4.rb:3:in `up'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:571:in `up'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:611:in `exec_migration'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:591:in `block in migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:590:in `migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:768:in `migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:1023:in `block in execute_migration_in_transaction'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:1071:in `ddl_transaction'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:1022:in `execute_migration_in_transaction'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:984:in `block in migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:980:in `each'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:980:in `migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:823:in `up'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/migration.rb:801:in `migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.11.3/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/usr/src/nbgallery/vendor/bundle/ruby/2.4.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

```

Indeed, the column do not exists on mysql.

```
SHOW COLUMNS FROM clicks;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | int(11)      | NO   | PRI | NULL    | auto_increment |
| user_id     | int(11)      | NO   | MUL | NULL    |                |
| org         | varchar(191) | YES  |     | NULL    |                |
| action      | varchar(191) | NO   |     | NULL    |                |
| notebook_id | int(11)      | YES  | MUL | NULL    |                |
| tracking    | varchar(191) | YES  |     | NULL    |                |
| created_at  | datetime     | NO   |     | NULL    |                |
| updated_at  | datetime     | NO   |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+
8 rows in set (0.01 sec)

```
This migration has others **DROP** actions on other tables (for example code_cells, notebooks, etc.) and all are with the same error because the column do not exists.

**Comment by mcrutch** [comment]
I thought I fixed this in code, but might not have deployed a new container, will check on that
